#define KONDAMASK 1
#if KONDAMASK
#define KONDAMASK_CACHE_ACCESSES_CSV 1

#define KONDAMASK_INPUT_CACHE_DECAY 1000
#define KONDAMASK_TEXTURE_CACHE_L0_DECAY 1000
#define KONDAMASK_TEXTURE_CACHE_L1_DECAY 1000
#define KONDAMASK_Z_CACHE_DECAY 1000
#define KONDAMASK_COLOR_CACHE_DECAY 1000000

#else
#define KONDAMASK_CACHE_ACCESSES_CSV 0
#define KONDAMASK_CACHE_DECAY_ENABLED 0
#endif
